export const GET_DATA_OF_DASHBOARD_1 = "GET_DATA_OF_DASHBOARD_1";
export const GET_DATA_OF_DASHBOARD_2 = "GET_DATA_OF_DASHBOARD_2";
export const GET_DATA_OF_DASHBOARD_3 = "GET_DATA_OF_DASHBOARD_3";
export const GET_DATA_OF_DASHBOARD_4 = "GET_DATA_OF_DASHBOARD_4";
